/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Arena.Messages;

import Metods.Stats;

/**
 *
 * @author Petr
 */
public class EnemyStatsDialog extends javax.swing.JDialog {

    /**
     * Creates new form EnemyStats
     */
    public EnemyStatsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Stats stats = new Stats();
        String[] enemyStats = stats.enemy(0);
        changableStatsName.setText(enemyStats[0]);
        changableStatsHP.setText(enemyStats[5]);
        changableStatsMP.setText(enemyStats[6]);
        changableStatsSTR.setText(enemyStats[1]);
        changableStatsDEX.setText(enemyStats[2]);
        changableStatsINT.setText(enemyStats[3]);
        changableStatsVIT.setText(enemyStats[4]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enemyStatsName = new javax.swing.JLabel();
        enemyStatsHP = new javax.swing.JLabel();
        enemyStatsMP = new javax.swing.JLabel();
        enemyStatsSTR = new javax.swing.JLabel();
        enemyStatsDEX = new javax.swing.JLabel();
        enemyStatsINT = new javax.swing.JLabel();
        enemyStatsVIT = new javax.swing.JLabel();
        changableStatsName = new javax.swing.JLabel();
        changableStatsHP = new javax.swing.JLabel();
        changableStatsMP = new javax.swing.JLabel();
        changableStatsSTR = new javax.swing.JLabel();
        changableStatsDEX = new javax.swing.JLabel();
        changableStatsINT = new javax.swing.JLabel();
        changableStatsVIT = new javax.swing.JLabel();
        enemyStatsEnemyStats = new javax.swing.JLabel();
        enemyStatsButtonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        enemyStatsName.setText("Name:");

        enemyStatsHP.setText("Hp:");

        enemyStatsMP.setText("MP:");

        enemyStatsSTR.setText("STR:");

        enemyStatsDEX.setText("DEX:");

        enemyStatsINT.setText("INT:");

        enemyStatsVIT.setText("VIT:");

        changableStatsName.setText("jLabel8");

        changableStatsHP.setText("jLabel9");

        changableStatsMP.setText("jLabel10");

        changableStatsSTR.setText("jLabel11");

        changableStatsDEX.setText("jLabel12");

        changableStatsINT.setText("jLabel13");

        changableStatsVIT.setText("jLabel14");

        enemyStatsEnemyStats.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enemyStatsEnemyStats.setText("Enemy Stats");

        enemyStatsButtonBack.setText("OK");
        enemyStatsButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enemyStatsButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enemyStatsEnemyStats)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(enemyStatsButtonBack))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(enemyStatsVIT)
                            .addComponent(enemyStatsINT)
                            .addComponent(enemyStatsDEX)
                            .addComponent(enemyStatsSTR)
                            .addComponent(enemyStatsMP)
                            .addComponent(enemyStatsHP)
                            .addComponent(enemyStatsName))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(changableStatsName)
                            .addComponent(changableStatsHP)
                            .addComponent(changableStatsMP)
                            .addComponent(changableStatsSTR)
                            .addComponent(changableStatsDEX)
                            .addComponent(changableStatsINT)
                            .addComponent(changableStatsVIT))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enemyStatsEnemyStats)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(changableStatsName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(changableStatsHP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(changableStatsMP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(changableStatsSTR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(changableStatsDEX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(changableStatsINT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(changableStatsVIT))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enemyStatsName, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enemyStatsHP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enemyStatsMP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enemyStatsSTR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enemyStatsDEX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enemyStatsINT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enemyStatsVIT)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enemyStatsButtonBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enemyStatsButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enemyStatsButtonBackActionPerformed
      this.dispose();
    }//GEN-LAST:event_enemyStatsButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnemyStatsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnemyStatsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnemyStatsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnemyStatsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EnemyStatsDialog dialog = new EnemyStatsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel changableStatsDEX;
    private javax.swing.JLabel changableStatsHP;
    private javax.swing.JLabel changableStatsINT;
    private javax.swing.JLabel changableStatsMP;
    private javax.swing.JLabel changableStatsName;
    private javax.swing.JLabel changableStatsSTR;
    private javax.swing.JLabel changableStatsVIT;
    private javax.swing.JButton enemyStatsButtonBack;
    private javax.swing.JLabel enemyStatsDEX;
    private javax.swing.JLabel enemyStatsEnemyStats;
    private javax.swing.JLabel enemyStatsHP;
    private javax.swing.JLabel enemyStatsINT;
    private javax.swing.JLabel enemyStatsMP;
    private javax.swing.JLabel enemyStatsName;
    private javax.swing.JLabel enemyStatsSTR;
    private javax.swing.JLabel enemyStatsVIT;
    // End of variables declaration//GEN-END:variables
}
