/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Arena;

import Arena.Messages.CustomMessage;
import Arena.Messages.EnemyStatsDialog;
import Arena.Messages.NewGameDialog;
import Arena.Messages.MessageWithInput;
import Metods.Enemies;
import Metods.Fight;
import Metods.Stats;
import Metods.Utilities;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Petr
 */
public class MainClass extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MainClass() {
        initComponents();
        reloadHeroStats();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dificultyButtonGroup = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        heroStatsPanel = new javax.swing.JPanel();
        nameLabelName = new javax.swing.JLabel();
        nameLabelLevel = new javax.swing.JLabel();
        nameLabelHP = new javax.swing.JLabel();
        nameLabelMP = new javax.swing.JLabel();
        nameLabelSTR = new javax.swing.JLabel();
        nameLabelDEX = new javax.swing.JLabel();
        nameLabelVIT = new javax.swing.JLabel();
        nameLabelINT = new javax.swing.JLabel();
        nameLabelMoney = new javax.swing.JLabel();
        nameLabelWeapon = new javax.swing.JLabel();
        nameLabelArmor = new javax.swing.JLabel();
        nameLabelShield = new javax.swing.JLabel();
        heroStatsButtonBag = new javax.swing.JButton();
        changableLabelName = new javax.swing.JLabel();
        changableLabelLevel = new javax.swing.JLabel();
        changableLabelHP = new javax.swing.JLabel();
        changableLabelMP = new javax.swing.JLabel();
        changableLabelSTR = new javax.swing.JLabel();
        changableLabelDEX = new javax.swing.JLabel();
        changableLabelVIT = new javax.swing.JLabel();
        changableLabelINT = new javax.swing.JLabel();
        changableLabelMoney = new javax.swing.JLabel();
        changableLabelWeapon = new javax.swing.JLabel();
        changableLabelShield = new javax.swing.JLabel();
        changableLabelArmor = new javax.swing.JLabel();
        nameLabelHeroStats = new javax.swing.JLabel();
        panelMainMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mainMenuArenaMenu = new javax.swing.JPanel();
        mainMenuArenaMenuButtonFight = new javax.swing.JButton();
        mainMenuArenaMenuButtonNextOpponent = new javax.swing.JButton();
        mainMenuArenaMenuButtonArenaLevel = new javax.swing.JButton();
        mainMenuArenaMenuButtonEnemyStats = new javax.swing.JButton();
        mainMenuArenaMenuComboBoxOpponentSelect = new javax.swing.JComboBox();
        mainMenuArenaMenuButtonOpponentConfirm = new javax.swing.JButton();
        mainMenuButtonArena = new javax.swing.JButton();
        mainMenuButtonShop = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        mainMenuShopMenu = new javax.swing.JPanel();
        mainMenuShopMenuButtonBuy = new javax.swing.JButton();
        mainMenuShopMenuButtonSell = new javax.swing.JButton();
        mainMenuButtonHospital = new javax.swing.JButton();
        mainMenuButtonNotYET = new javax.swing.JButton();
        panelArenaMenu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        arenaMenuButtonLightAttack = new javax.swing.JButton();
        arenaMenuButtonNormalAttack = new javax.swing.JButton();
        arenaMenuButtonHeavyAttack = new javax.swing.JButton();
        arenaMenuButtonBack = new javax.swing.JButton();
        arenaMenuAttackLog = new javax.swing.JScrollPane();
        arenaMenuAttackLogField = new javax.swing.JTextArea();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        panelShopMenu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        shopMenuButtonBack = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        shopMenuButtonBuy = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        shopMenuListField = new javax.swing.JList();
        shopMenuLabelItemName = new javax.swing.JLabel();
        shopMenuLabelItemSTR = new javax.swing.JLabel();
        shopMenuLabelItemDEX = new javax.swing.JLabel();
        shopMenuLabelItemINT = new javax.swing.JLabel();
        shopMenuLabelItemVIT = new javax.swing.JLabel();
        shopMenuLabelItemDMG = new javax.swing.JLabel();
        shopMenuLabelItemDEF = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        shopMenuLabelItemNameStats = new javax.swing.JLabel();
        shopMenuLabelItemSTRStats = new javax.swing.JLabel();
        shopMenuLabelItemDEXStats = new javax.swing.JLabel();
        shopMenuLabelItemINTStats = new javax.swing.JLabel();
        shopMenuLabelItemVITStats = new javax.swing.JLabel();
        shopMenuLabelItemDMGStats = new javax.swing.JLabel();
        shopMenuLabelItemDEFStats = new javax.swing.JLabel();
        shopMenuLabelItemPriceStats = new javax.swing.JLabel();
        topMenuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuFileNewGame = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu1 = new javax.swing.JMenu();
        switchButtonDifficultyEasy = new javax.swing.JRadioButtonMenuItem();
        switchButtonDifficultyNormal = new javax.swing.JRadioButtonMenuItem();
        switchButtonDifficultyHard = new javax.swing.JRadioButtonMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuFileSave = new javax.swing.JMenuItem();
        menuFileLoad = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuFileEndGame = new javax.swing.JMenuItem();
        menuHero = new javax.swing.JMenu();
        menuSettings = new javax.swing.JMenu();
        testButton = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();
        addLevel = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        testMenuAddStr = new javax.swing.JMenuItem();
        testMenuAddDex = new javax.swing.JMenuItem();
        testMenuAddInt = new javax.swing.JMenuItem();
        testMenuAddVit = new javax.swing.JMenuItem();
        addMoney = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Arena Fighter");
        setBackground(new java.awt.Color(0, 52, 130));
        setForeground(java.awt.Color.cyan);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        heroStatsPanel.setBackground(new java.awt.Color(204, 204, 204));
        heroStatsPanel.setMaximumSize(new java.awt.Dimension(213, 350));
        heroStatsPanel.setPreferredSize(new java.awt.Dimension(213, 380));

        nameLabelName.setText("Name:");

        nameLabelLevel.setText("Level:");

        nameLabelHP.setText("HP:");

        nameLabelMP.setText("MP:");

        nameLabelSTR.setText("STR:");

        nameLabelDEX.setText("DEX:");

        nameLabelVIT.setText("VIT:");

        nameLabelINT.setText("INT:");

        nameLabelMoney.setText("Money:");

        nameLabelWeapon.setText("Weapon:");

        nameLabelArmor.setText("Armor:");

        nameLabelShield.setText("Shield:");

        heroStatsButtonBag.setText("Bag");
        heroStatsButtonBag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heroStatsButtonBagActionPerformed(evt);
            }
        });

        changableLabelName.setText("Argus Pyrrhus");
        changableLabelName.setMaximumSize(new java.awt.Dimension(130, 10));
        changableLabelName.setName(""); // NOI18N
        changableLabelName.setPreferredSize(new java.awt.Dimension(120, 15));

        changableLabelLevel.setMaximumSize(new java.awt.Dimension(130, 10));
        changableLabelLevel.setName(""); // NOI18N
        changableLabelLevel.setPreferredSize(new java.awt.Dimension(120, 15));

        changableLabelHP.setMaximumSize(new java.awt.Dimension(130, 10));
        changableLabelHP.setPreferredSize(new java.awt.Dimension(120, 15));

        changableLabelMP.setMaximumSize(new java.awt.Dimension(130, 10));
        changableLabelMP.setPreferredSize(new java.awt.Dimension(120, 15));

        changableLabelSTR.setMaximumSize(new java.awt.Dimension(130, 10));
        changableLabelSTR.setName(""); // NOI18N
        changableLabelSTR.setPreferredSize(new java.awt.Dimension(120, 15));

        changableLabelDEX.setMaximumSize(new java.awt.Dimension(130, 10));
        changableLabelDEX.setName(""); // NOI18N
        changableLabelDEX.setPreferredSize(new java.awt.Dimension(120, 15));

        changableLabelVIT.setMaximumSize(new java.awt.Dimension(130, 10));
        changableLabelVIT.setName(""); // NOI18N
        changableLabelVIT.setPreferredSize(new java.awt.Dimension(120, 15));

        changableLabelINT.setMaximumSize(new java.awt.Dimension(130, 10));
        changableLabelINT.setName(""); // NOI18N
        changableLabelINT.setPreferredSize(new java.awt.Dimension(120, 15));

        changableLabelMoney.setMaximumSize(new java.awt.Dimension(130, 10));
        changableLabelMoney.setName(""); // NOI18N
        changableLabelMoney.setPreferredSize(new java.awt.Dimension(120, 15));

        changableLabelWeapon.setMaximumSize(new java.awt.Dimension(130, 10));
        changableLabelWeapon.setName(""); // NOI18N
        changableLabelWeapon.setPreferredSize(new java.awt.Dimension(120, 15));

        changableLabelShield.setMaximumSize(new java.awt.Dimension(130, 10));
        changableLabelShield.setName(""); // NOI18N
        changableLabelShield.setPreferredSize(new java.awt.Dimension(120, 15));

        changableLabelArmor.setMaximumSize(new java.awt.Dimension(130, 10));
        changableLabelArmor.setName(""); // NOI18N
        changableLabelArmor.setPreferredSize(new java.awt.Dimension(120, 15));

        nameLabelHeroStats.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nameLabelHeroStats.setText("Hero Stats");
        nameLabelHeroStats.setPreferredSize(new java.awt.Dimension(130, 15));

        javax.swing.GroupLayout heroStatsPanelLayout = new javax.swing.GroupLayout(heroStatsPanel);
        heroStatsPanel.setLayout(heroStatsPanelLayout);
        heroStatsPanelLayout.setHorizontalGroup(
            heroStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, heroStatsPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(heroStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(heroStatsPanelLayout.createSequentialGroup()
                        .addGroup(heroStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabelHP)
                            .addComponent(nameLabelName)
                            .addComponent(nameLabelLevel))
                        .addGap(32, 32, 32)
                        .addGroup(heroStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(changableLabelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(changableLabelHP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(changableLabelLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(heroStatsPanelLayout.createSequentialGroup()
                        .addGroup(heroStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabelWeapon)
                            .addComponent(nameLabelShield)
                            .addComponent(nameLabelArmor))
                        .addGap(18, 18, 18)
                        .addGroup(heroStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(changableLabelArmor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(heroStatsButtonBag, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(changableLabelShield, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(changableLabelWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(heroStatsPanelLayout.createSequentialGroup()
                        .addGroup(heroStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabelSTR)
                            .addComponent(nameLabelDEX)
                            .addComponent(nameLabelVIT)
                            .addComponent(nameLabelINT)
                            .addComponent(nameLabelMoney)
                            .addComponent(nameLabelMP))
                        .addGap(27, 27, 27)
                        .addGroup(heroStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(changableLabelVIT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(changableLabelDEX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(changableLabelSTR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(changableLabelMP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(changableLabelINT, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changableLabelMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(heroStatsPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(nameLabelHeroStats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        heroStatsPanelLayout.setVerticalGroup(
            heroStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(heroStatsPanelLayout.createSequentialGroup()
                .addComponent(nameLabelHeroStats, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(heroStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabelName)
                    .addComponent(changableLabelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(heroStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabelLevel)
                    .addComponent(changableLabelLevel, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(heroStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameLabelHP)
                    .addComponent(changableLabelHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(heroStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabelMP)
                    .addComponent(changableLabelMP, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(heroStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabelSTR)
                    .addComponent(changableLabelSTR, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(heroStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabelDEX)
                    .addComponent(changableLabelDEX, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(heroStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabelVIT)
                    .addComponent(changableLabelVIT, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(heroStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameLabelINT)
                    .addComponent(changableLabelINT, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(heroStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabelMoney)
                    .addComponent(changableLabelMoney, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(heroStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabelWeapon)
                    .addComponent(changableLabelWeapon, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(heroStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabelShield)
                    .addComponent(changableLabelShield, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(heroStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabelArmor)
                    .addComponent(changableLabelArmor, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(heroStatsButtonBag)
                .addGap(52, 52, 52))
        );

        getContentPane().add(heroStatsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, -1, 400));

        panelMainMenu.setMaximumSize(new java.awt.Dimension(800, 400));
        panelMainMenu.setPreferredSize(new java.awt.Dimension(600, 380));
        panelMainMenu.setVerifyInputWhenFocusTarget(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Main Menu");
        jLabel1.setPreferredSize(new java.awt.Dimension(191, 44));

        mainMenuArenaMenuButtonFight.setText("Fight");
        mainMenuArenaMenuButtonFight.setPreferredSize(new java.awt.Dimension(150, 50));
        mainMenuArenaMenuButtonFight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuArenaMenuButtonFightActionPerformed(evt);
            }
        });

        mainMenuArenaMenuButtonNextOpponent.setText("Next Opponent");
        mainMenuArenaMenuButtonNextOpponent.setPreferredSize(new java.awt.Dimension(100, 50));
        mainMenuArenaMenuButtonNextOpponent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuArenaMenuButtonNextOpponentActionPerformed(evt);
            }
        });

        mainMenuArenaMenuButtonArenaLevel.setText("Arena Level");
        mainMenuArenaMenuButtonArenaLevel.setPreferredSize(new java.awt.Dimension(150, 50));
        mainMenuArenaMenuButtonArenaLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuArenaMenuButtonArenaLevelActionPerformed(evt);
            }
        });

        mainMenuArenaMenuButtonEnemyStats.setText("Enemy Stats");
        mainMenuArenaMenuButtonEnemyStats.setPreferredSize(new java.awt.Dimension(150, 50));
        mainMenuArenaMenuButtonEnemyStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuArenaMenuButtonEnemyStatsActionPerformed(evt);
            }
        });

        mainMenuArenaMenuButtonOpponentConfirm.setText("Thats my opponent");
        mainMenuArenaMenuButtonOpponentConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuArenaMenuButtonOpponentConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainMenuArenaMenuLayout = new javax.swing.GroupLayout(mainMenuArenaMenu);
        mainMenuArenaMenu.setLayout(mainMenuArenaMenuLayout);
        mainMenuArenaMenuLayout.setHorizontalGroup(
            mainMenuArenaMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuArenaMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainMenuArenaMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainMenuArenaMenuButtonFight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainMenuArenaMenuLayout.createSequentialGroup()
                        .addGroup(mainMenuArenaMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mainMenuArenaMenuButtonArenaLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mainMenuArenaMenuButtonNextOpponent, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(mainMenuArenaMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mainMenuArenaMenuComboBoxOpponentSelect, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mainMenuArenaMenuButtonOpponentConfirm)))
                    .addComponent(mainMenuArenaMenuButtonEnemyStats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainMenuArenaMenuLayout.setVerticalGroup(
            mainMenuArenaMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuArenaMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainMenuArenaMenuButtonFight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mainMenuArenaMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainMenuArenaMenuLayout.createSequentialGroup()
                        .addComponent(mainMenuArenaMenuComboBoxOpponentSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mainMenuArenaMenuButtonOpponentConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mainMenuArenaMenuLayout.createSequentialGroup()
                        .addComponent(mainMenuArenaMenuButtonNextOpponent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mainMenuArenaMenuButtonArenaLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mainMenuArenaMenuButtonEnemyStats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        mainMenuArenaMenuComboBoxOpponentSelect.setVisible(false);
        mainMenuArenaMenuButtonOpponentConfirm.setVisible(false);

        mainMenuButtonArena.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mainMenuButtonArena.setText("Arena");
        mainMenuButtonArena.setPreferredSize(new java.awt.Dimension(80, 40));
        mainMenuButtonArena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButtonArenaActionPerformed(evt);
            }
        });

        mainMenuButtonShop.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mainMenuButtonShop.setText("Shop");
        mainMenuButtonShop.setPreferredSize(new java.awt.Dimension(80, 40));
        mainMenuButtonShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButtonShopActionPerformed(evt);
            }
        });

        mainMenuShopMenu.setPreferredSize(new java.awt.Dimension(338, 265));

        mainMenuShopMenuButtonBuy.setText("Buy");
        mainMenuShopMenuButtonBuy.setPreferredSize(new java.awt.Dimension(150, 50));
        mainMenuShopMenuButtonBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuShopMenuButtonBuyActionPerformed(evt);
            }
        });

        mainMenuShopMenuButtonSell.setText("Sell");
        mainMenuShopMenuButtonSell.setPreferredSize(new java.awt.Dimension(150, 50));
        mainMenuShopMenuButtonSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuShopMenuButtonSellActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainMenuShopMenuLayout = new javax.swing.GroupLayout(mainMenuShopMenu);
        mainMenuShopMenu.setLayout(mainMenuShopMenuLayout);
        mainMenuShopMenuLayout.setHorizontalGroup(
            mainMenuShopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuShopMenuLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(mainMenuShopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainMenuShopMenuButtonBuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainMenuShopMenuButtonSell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        mainMenuShopMenuLayout.setVerticalGroup(
            mainMenuShopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuShopMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainMenuShopMenuButtonBuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mainMenuShopMenuButtonSell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(249, Short.MAX_VALUE))
        );

        mainMenuButtonHospital.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mainMenuButtonHospital.setText("Hospital");
        mainMenuButtonHospital.setPreferredSize(new java.awt.Dimension(80, 40));
        mainMenuButtonHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButtonHospitalActionPerformed(evt);
            }
        });

        mainMenuButtonNotYET.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mainMenuButtonNotYET.setText("---");
        mainMenuButtonNotYET.setPreferredSize(new java.awt.Dimension(80, 40));
        mainMenuButtonNotYET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButtonNotYETActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMainMenuLayout = new javax.swing.GroupLayout(panelMainMenu);
        panelMainMenu.setLayout(panelMainMenuLayout);
        panelMainMenuLayout.setHorizontalGroup(
            panelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mainMenuButtonArena, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mainMenuButtonShop, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mainMenuButtonHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainMenuButtonNotYET, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mainMenuArenaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(panelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelMainMenuLayout.createSequentialGroup()
                    .addGap(229, 229, 229)
                    .addComponent(mainMenuShopMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(13, Short.MAX_VALUE)))
        );
        panelMainMenuLayout.setVerticalGroup(
            panelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainMenuArenaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelMainMenuLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mainMenuButtonArena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mainMenuButtonShop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mainMenuButtonHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mainMenuButtonNotYET, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(filler1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(panelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelMainMenuLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(mainMenuShopMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        mainMenuArenaMenu.setVisible(false);
        mainMenuShopMenu.setVisible(false);

        getContentPane().add(panelMainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 580, 400));

        panelArenaMenu.setPreferredSize(new java.awt.Dimension(600, 380));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Arena Menu");

        arenaMenuButtonLightAttack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        arenaMenuButtonLightAttack.setText("Light Attack");
        arenaMenuButtonLightAttack.setPreferredSize(new java.awt.Dimension(80, 40));
        arenaMenuButtonLightAttack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arenaMenuButtonLightAttackActionPerformed(evt);
            }
        });

        arenaMenuButtonNormalAttack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        arenaMenuButtonNormalAttack.setText("Heavy Attack");
        arenaMenuButtonNormalAttack.setPreferredSize(new java.awt.Dimension(80, 40));
        arenaMenuButtonNormalAttack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arenaMenuButtonNormalAttackActionPerformed(evt);
            }
        });

        arenaMenuButtonHeavyAttack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        arenaMenuButtonHeavyAttack.setText("Normal Attack");
        arenaMenuButtonHeavyAttack.setPreferredSize(new java.awt.Dimension(80, 40));
        arenaMenuButtonHeavyAttack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arenaMenuButtonHeavyAttackActionPerformed(evt);
            }
        });

        arenaMenuButtonBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        arenaMenuButtonBack.setText("Back to main menu");
        arenaMenuButtonBack.setPreferredSize(new java.awt.Dimension(80, 40));
        arenaMenuButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arenaMenuButtonBackActionPerformed(evt);
            }
        });

        arenaMenuAttackLogField.setColumns(1);
        arenaMenuAttackLogField.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        arenaMenuAttackLog.setViewportView(arenaMenuAttackLogField);

        javax.swing.GroupLayout panelArenaMenuLayout = new javax.swing.GroupLayout(panelArenaMenu);
        panelArenaMenu.setLayout(panelArenaMenuLayout);
        panelArenaMenuLayout.setHorizontalGroup(
            panelArenaMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArenaMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelArenaMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(arenaMenuButtonHeavyAttack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(arenaMenuButtonNormalAttack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(arenaMenuButtonLightAttack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(arenaMenuButtonBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(arenaMenuAttackLog, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelArenaMenuLayout.setVerticalGroup(
            panelArenaMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelArenaMenuLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(arenaMenuAttackLog, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
            .addComponent(filler2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelArenaMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(arenaMenuButtonLightAttack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(arenaMenuButtonHeavyAttack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(arenaMenuButtonNormalAttack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(arenaMenuButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        arenaMenuAttackLog.setVisible(false);

        getContentPane().add(panelArenaMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 580, 400));
        panelArenaMenu.setVisible(false);

        panelShopMenu.setPreferredSize(new java.awt.Dimension(600, 380));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("Shop Menu");

        shopMenuButtonBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        shopMenuButtonBack.setText("Back to main menu");
        shopMenuButtonBack.setPreferredSize(new java.awt.Dimension(80, 40));
        shopMenuButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shopMenuButtonBackActionPerformed(evt);
            }
        });

        shopMenuButtonBuy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        shopMenuButtonBuy.setPreferredSize(new java.awt.Dimension(80, 40));
        shopMenuButtonBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shopMenuButtonBuyActionPerformed(evt);
            }
        });

        shopMenuListField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        shopMenuListField.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        shopMenuListField.setToolTipText("");
        shopMenuListField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        shopMenuListField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shopMenuListFieldMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                shopMenuListFieldMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(shopMenuListField);

        shopMenuLabelItemName.setText("Name:");

        shopMenuLabelItemSTR.setText("STR:");

        shopMenuLabelItemDEX.setText("DEX:");

        shopMenuLabelItemINT.setText("INT:");

        shopMenuLabelItemVIT.setText("VIT:");

        shopMenuLabelItemDMG.setText("DMG:");

        shopMenuLabelItemDEF.setText("DEF:");

        Price.setText("Price:");

        javax.swing.GroupLayout panelShopMenuLayout = new javax.swing.GroupLayout(panelShopMenu);
        panelShopMenu.setLayout(panelShopMenuLayout);
        panelShopMenuLayout.setHorizontalGroup(
            panelShopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShopMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelShopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelShopMenuLayout.createSequentialGroup()
                        .addGroup(panelShopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(shopMenuButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShopMenuLayout.createSequentialGroup()
                        .addComponent(shopMenuButtonBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelShopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelShopMenuLayout.createSequentialGroup()
                        .addComponent(Price)
                        .addGap(18, 18, 18)
                        .addComponent(shopMenuLabelItemPriceStats))
                    .addGroup(panelShopMenuLayout.createSequentialGroup()
                        .addGroup(panelShopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(shopMenuLabelItemName)
                            .addComponent(shopMenuLabelItemSTR)
                            .addComponent(shopMenuLabelItemDEX)
                            .addComponent(shopMenuLabelItemINT)
                            .addComponent(shopMenuLabelItemVIT)
                            .addComponent(shopMenuLabelItemDMG)
                            .addComponent(shopMenuLabelItemDEF))
                        .addGap(18, 18, 18)
                        .addGroup(panelShopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(shopMenuLabelItemDEFStats)
                            .addComponent(shopMenuLabelItemDMGStats)
                            .addComponent(shopMenuLabelItemVITStats)
                            .addComponent(shopMenuLabelItemINTStats)
                            .addComponent(shopMenuLabelItemDEXStats)
                            .addComponent(shopMenuLabelItemSTRStats)
                            .addComponent(shopMenuLabelItemNameStats))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        panelShopMenuLayout.setVerticalGroup(
            panelShopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(filler3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelShopMenuLayout.createSequentialGroup()
                .addGroup(panelShopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelShopMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(shopMenuButtonBuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162)
                        .addComponent(shopMenuButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelShopMenuLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(panelShopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shopMenuLabelItemName)
                            .addComponent(shopMenuLabelItemNameStats))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelShopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shopMenuLabelItemSTR)
                            .addComponent(shopMenuLabelItemSTRStats))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelShopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shopMenuLabelItemDEX)
                            .addComponent(shopMenuLabelItemDEXStats))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelShopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shopMenuLabelItemINT)
                            .addComponent(shopMenuLabelItemINTStats))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelShopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shopMenuLabelItemVIT)
                            .addComponent(shopMenuLabelItemVITStats))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelShopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shopMenuLabelItemDMG, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shopMenuLabelItemDMGStats))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelShopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shopMenuLabelItemDEF)
                            .addComponent(shopMenuLabelItemDEFStats))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelShopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Price)
                            .addComponent(shopMenuLabelItemPriceStats))))
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShopMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        getContentPane().add(panelShopMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 580, 400));
        panelShopMenu.setVisible(false);

        topMenuBar.setPreferredSize(new java.awt.Dimension(178, 20));

        menuFile.setText("File");

        menuFileNewGame.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK));
        menuFileNewGame.setText("New Game");
        menuFileNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFileNewGameActionPerformed(evt);
            }
        });
        menuFile.add(menuFileNewGame);
        menuFile.add(jSeparator1);

        jMenu1.setText("Difficulty");

        dificultyButtonGroup.add(switchButtonDifficultyEasy);
        switchButtonDifficultyEasy.setText("Easy");
        switchButtonDifficultyEasy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchButtonDifficultyEasyActionPerformed(evt);
            }
        });
        jMenu1.add(switchButtonDifficultyEasy);

        dificultyButtonGroup.add(switchButtonDifficultyNormal);
        switchButtonDifficultyNormal.setSelected(true);
        switchButtonDifficultyNormal.setText("Normal");
        switchButtonDifficultyNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchButtonDifficultyNormalActionPerformed(evt);
            }
        });
        jMenu1.add(switchButtonDifficultyNormal);

        dificultyButtonGroup.add(switchButtonDifficultyHard);
        switchButtonDifficultyHard.setText("Hard");
        switchButtonDifficultyHard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchButtonDifficultyHardActionPerformed(evt);
            }
        });
        jMenu1.add(switchButtonDifficultyHard);

        menuFile.add(jMenu1);
        menuFile.add(jSeparator3);

        menuFileSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        menuFileSave.setText("Save Game");
        menuFileSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFileSaveActionPerformed(evt);
            }
        });
        menuFile.add(menuFileSave);

        menuFileLoad.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_MASK));
        menuFileLoad.setText("Load Game");
        menuFileLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFileLoadActionPerformed(evt);
            }
        });
        menuFile.add(menuFileLoad);
        menuFile.add(jSeparator2);

        menuFileEndGame.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuFileEndGame.setText("Exit Game");
        menuFileEndGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFileEndGameActionPerformed(evt);
            }
        });
        menuFile.add(menuFileEndGame);

        topMenuBar.add(menuFile);

        menuHero.setText("Hero");
        topMenuBar.add(menuHero);

        menuSettings.setText("Settings");

        testButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_NUMPAD9, 0));
        testButton.setText("Test");
        testButton.setHideActionText(true);
        testButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testButtonActionPerformed(evt);
            }
        });
        menuSettings.add(testButton);

        topMenuBar.add(menuSettings);

        jMenu2.setText("Test mode");

        addLevel.setText("Add Level");
        addLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLevelActionPerformed(evt);
            }
        });
        jMenu2.add(addLevel);

        jMenu3.setText("Add Stat");

        testMenuAddStr.setText("Strenght");
        testMenuAddStr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testMenuAddStrActionPerformed(evt);
            }
        });
        jMenu3.add(testMenuAddStr);

        testMenuAddDex.setText("Dexterity");
        testMenuAddDex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testMenuAddDexActionPerformed(evt);
            }
        });
        jMenu3.add(testMenuAddDex);

        testMenuAddInt.setText("Inteligence");
        testMenuAddInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testMenuAddIntActionPerformed(evt);
            }
        });
        jMenu3.add(testMenuAddInt);

        testMenuAddVit.setText("Vitality");
        testMenuAddVit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testMenuAddVitActionPerformed(evt);
            }
        });
        jMenu3.add(testMenuAddVit);

        jMenu2.add(jMenu3);

        addMoney.setText("Add Money");
        addMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMoneyActionPerformed(evt);
            }
        });
        jMenu2.add(addMoney);

        topMenuBar.add(jMenu2);
        jMenu2.setVisible(false);

        setJMenuBar(topMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuFileSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFileSaveActionPerformed
        SaveForm sf = new SaveForm();
        sf.setVisible(true);


    }//GEN-LAST:event_menuFileSaveActionPerformed

    private void menuFileNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFileNewGameActionPerformed
       NewGameDialog newGameDialog = new NewGameDialog(this, true);
        newGameDialog.setVisible(true);
        if (newGameDialog.getEndStatus().equals("Yes")) {
            this.dispose();          
        }     
    }//GEN-LAST:event_menuFileNewGameActionPerformed

    private void testButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testButtonActionPerformed
        if (testButton.isSelected() == true) {
            testMode = true;
            jMenu2.setVisible(true);
        } else {
            jMenu2.setVisible(false);
        }

    }//GEN-LAST:event_testButtonActionPerformed

    private void switchButtonDifficultyNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchButtonDifficultyNormalActionPerformed

        Utilities.setDificulty(switchButtonDifficultyNormal.getText());
    }//GEN-LAST:event_switchButtonDifficultyNormalActionPerformed

    private void switchButtonDifficultyEasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchButtonDifficultyEasyActionPerformed

        Utilities.setDificulty(switchButtonDifficultyEasy.getText());
    }//GEN-LAST:event_switchButtonDifficultyEasyActionPerformed

    private void switchButtonDifficultyHardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchButtonDifficultyHardActionPerformed

        Utilities.setDificulty(switchButtonDifficultyHard.getText());
    }//GEN-LAST:event_switchButtonDifficultyHardActionPerformed

    private void menuFileEndGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFileEndGameActionPerformed
        this.dispose();
    }//GEN-LAST:event_menuFileEndGameActionPerformed

    private void heroStatsButtonBagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heroStatsButtonBagActionPerformed
        Arena.Messages.BagDialog bagDialog = new Arena.Messages.BagDialog(this, true);
        bagDialog.setVisible(true);
    }//GEN-LAST:event_heroStatsButtonBagActionPerformed

    private void menuFileLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFileLoadActionPerformed
        LoadForm lf = new LoadForm();
        lf.setVisible(true);
    }//GEN-LAST:event_menuFileLoadActionPerformed

    private void arenaMenuButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arenaMenuButtonBackActionPerformed
        panelArenaMenu.setVisible(false);
        panelMainMenu.setVisible(true);
    }//GEN-LAST:event_arenaMenuButtonBackActionPerformed

    private void arenaMenuButtonHeavyAttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arenaMenuButtonHeavyAttackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arenaMenuButtonHeavyAttackActionPerformed

    private void arenaMenuButtonNormalAttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arenaMenuButtonNormalAttackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arenaMenuButtonNormalAttackActionPerformed

    private void arenaMenuButtonLightAttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arenaMenuButtonLightAttackActionPerformed
        Fight fight = new Fight();

    }//GEN-LAST:event_arenaMenuButtonLightAttackActionPerformed

    private void addLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLevelActionPerformed
        MessageWithInput messageWithInput = new MessageWithInput(this, true, addLevel.getText());
        messageWithInput.setVisible(true);
        Metods.HeroStats.setLevel(Metods.HeroStats.getLevel() + messageWithInput.getInput());
    }//GEN-LAST:event_addLevelActionPerformed

    private void addMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMoneyActionPerformed
        MessageWithInput messageWithInput = new MessageWithInput(this, true, addMoney.getText());
        messageWithInput.setVisible(true);
        Metods.HeroStats.setMoney(Metods.HeroStats.getMoney() + messageWithInput.getInput());
    }//GEN-LAST:event_addMoneyActionPerformed

    private void mainMenuButtonArenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonArenaActionPerformed
        if (!mainMenuArenaMenu.isVisible()) {
            mainMenuShopMenu.setVisible(false);
            mainMenuArenaMenu.setVisible(true);
        } else {
            mainMenuArenaMenu.setVisible(false);
        }

    }//GEN-LAST:event_mainMenuButtonArenaActionPerformed

    private void mainMenuArenaMenuButtonOpponentConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuArenaMenuButtonOpponentConfirmActionPerformed
        Enemies.enemy(mainMenuArenaMenuComboBoxOpponentSelect.getSelectedIndex() + 1);
        mainMenuArenaMenuButtonOpponentConfirm.setVisible(false);
        mainMenuArenaMenuComboBoxOpponentSelect.setVisible(false);
    }//GEN-LAST:event_mainMenuArenaMenuButtonOpponentConfirmActionPerformed

    private void mainMenuArenaMenuButtonEnemyStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuArenaMenuButtonEnemyStatsActionPerformed
        EnemyStatsDialog esd = new EnemyStatsDialog(this, true);
        esd.setVisible(true);

    }//GEN-LAST:event_mainMenuArenaMenuButtonEnemyStatsActionPerformed

    private void mainMenuArenaMenuButtonArenaLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuArenaMenuButtonArenaLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mainMenuArenaMenuButtonArenaLevelActionPerformed

    private void mainMenuArenaMenuButtonNextOpponentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuArenaMenuButtonNextOpponentActionPerformed
        mainMenuArenaMenuComboBoxOpponentSelect.setModel(new DefaultComboBoxModel(Enemies.getEnemyList()));
        mainMenuArenaMenuButtonNextOpponent.setEnabled(false);
        mainMenuArenaMenuButtonOpponentConfirm.setVisible(true);
        mainMenuArenaMenuComboBoxOpponentSelect.setVisible(true);
    }//GEN-LAST:event_mainMenuArenaMenuButtonNextOpponentActionPerformed

    private void mainMenuArenaMenuButtonFightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuArenaMenuButtonFightActionPerformed
        panelArenaMenu.setVisible(true);
        panelMainMenu.setVisible(false);
    }//GEN-LAST:event_mainMenuArenaMenuButtonFightActionPerformed

    private void testMenuAddStrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testMenuAddStrActionPerformed
        MessageWithInput messageWithInput = new MessageWithInput(this, true, "ADD " + testMenuAddStr.getText());
        messageWithInput.setVisible(true);
        Metods.HeroStats.setStrenght(Metods.HeroStats.getStrenght() + Arena.Messages.MessageWithInput.getInput());
    }//GEN-LAST:event_testMenuAddStrActionPerformed

    private void testMenuAddVitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testMenuAddVitActionPerformed
        MessageWithInput messageWithInput = new MessageWithInput(this, true, "ADD " + testMenuAddVit.getText());
        messageWithInput.setVisible(true);
        Metods.HeroStats.setVitality(Metods.HeroStats.getVitality() + Arena.Messages.MessageWithInput.getInput());
    }//GEN-LAST:event_testMenuAddVitActionPerformed

    private void testMenuAddDexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testMenuAddDexActionPerformed
        MessageWithInput messageWithInput = new MessageWithInput(this, true, "ADD " + testMenuAddDex.getText());
        messageWithInput.setVisible(true);
        Metods.HeroStats.setDexterity(Metods.HeroStats.getDexterity() + Arena.Messages.MessageWithInput.getInput());
    }//GEN-LAST:event_testMenuAddDexActionPerformed

    private void testMenuAddIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testMenuAddIntActionPerformed
        MessageWithInput messageWithInput = new MessageWithInput(this, true, "ADD " + testMenuAddInt.getText());
        messageWithInput.setVisible(true);
        Metods.HeroStats.setInteligence(Metods.HeroStats.getInteligence() + Arena.Messages.MessageWithInput.getInput());
    }//GEN-LAST:event_testMenuAddIntActionPerformed

    private void mainMenuButtonShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonShopActionPerformed
        if (!mainMenuShopMenu.isVisible()) {
            mainMenuArenaMenu.setVisible(false);
            mainMenuShopMenu.setVisible(true);
        } else {
            mainMenuShopMenu.setVisible(false);
        }
    }//GEN-LAST:event_mainMenuButtonShopActionPerformed

    private void mainMenuShopMenuButtonBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuShopMenuButtonBuyActionPerformed
        setShopUserChoice("Buy");
        shopMenuButtonBuy.setText(getShopUserChoice());
        Metods.Shop.loadShop();
        Metods.Shop.getItemNames();
        shopMenuListField.setModel(Metods.Shop.getDefaultListModel());
        panelMainMenu.setVisible(false);
        panelShopMenu.setVisible(true);
    }//GEN-LAST:event_mainMenuShopMenuButtonBuyActionPerformed

    private void mainMenuShopMenuButtonSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuShopMenuButtonSellActionPerformed
        setShopUserChoice("Sell");
        shopMenuButtonBuy.setText(getShopUserChoice());
        panelMainMenu.setVisible(false);
        panelShopMenu.setVisible(true);
    }//GEN-LAST:event_mainMenuShopMenuButtonSellActionPerformed

    private void shopMenuButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shopMenuButtonBackActionPerformed
        Metods.Shop.removeInventory();

        panelShopMenu.setVisible(false);
        panelMainMenu.setVisible(true);


    }//GEN-LAST:event_shopMenuButtonBackActionPerformed

    private void mainMenuButtonHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonHospitalActionPerformed
        CustomMessage cm = new CustomMessage(this, true, "Under Construction", "This button is under construction");
        cm.setVisible(true);
    }//GEN-LAST:event_mainMenuButtonHospitalActionPerformed

    private void mainMenuButtonNotYETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonNotYETActionPerformed

        CustomMessage cm = new CustomMessage(this, true, "Under Construction", "This button is under construction");
        cm.setVisible(true);

    }//GEN-LAST:event_mainMenuButtonNotYETActionPerformed

    private void shopMenuButtonBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shopMenuButtonBuyActionPerformed
        int selected = shopMenuListField.getSelectedIndex();
        System.out.println(selected);
    }//GEN-LAST:event_shopMenuButtonBuyActionPerformed

    private void shopMenuListFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shopMenuListFieldMouseClicked

    }//GEN-LAST:event_shopMenuListFieldMouseClicked

    private void shopMenuListFieldMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shopMenuListFieldMouseReleased
        String[] item = Metods.Shop.getItemStats(shopMenuListField.getSelectedIndex() + 1);
        shopMenuLabelItemNameStats.setText(item[1]);
        shopMenuLabelItemSTRStats.setText(item[2]);
        shopMenuLabelItemDEXStats.setText(item[3]);
        shopMenuLabelItemINTStats.setText(item[4]);
        shopMenuLabelItemVITStats.setText(item[5]);
        shopMenuLabelItemDMGStats.setText(item[6]);
        shopMenuLabelItemDEFStats.setText(item[7]);
        shopMenuLabelItemPriceStats.setText(item[9]);
    }//GEN-LAST:event_shopMenuListFieldMouseReleased
    public final void reloadHeroStats() {
        Stats stats = new Stats();
        String[] heroStats = stats.hero();
        changableLabelSTR.setText(heroStats[0]);
        changableLabelINT.setText(heroStats[1]);
        changableLabelVIT.setText(heroStats[2]);
        changableLabelDEX.setText(heroStats[3]);
        changableLabelHP.setText(heroStats[4]);
        changableLabelMP.setText(heroStats[5]);
        changableLabelMoney.setText(heroStats[6]);
        changableLabelLevel.setText(heroStats[7]);
//        changableLabelExperiance.setText(heroStats[8]);
        changableLabelWeapon.setText(heroStats[9]);
        changableLabelShield.setText(heroStats[10]);
        changableLabelArmor.setText(heroStats[11]);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Metods.Utilities.systemInit();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainClass().setVisible(true);

            }
        });
    }
// <editor-fold defaultstate="collapsed" desc="Gettings and Settings">

    public String getShopUserChoice() {
        return shopUserChoice;
    }

    public void setShopUserChoice(String shopUserChoice) {
        this.shopUserChoice = shopUserChoice;
    }
// </editor-fold> 
// <editor-fold defaultstate="collapsed" desc="Variables">
    // user variables
    public boolean testMode = false;
    private String shopUserChoice;
    // end of user variables
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Price;
    private javax.swing.JMenuItem addLevel;
    private javax.swing.JMenuItem addMoney;
    private javax.swing.JScrollPane arenaMenuAttackLog;
    private javax.swing.JTextArea arenaMenuAttackLogField;
    private javax.swing.JButton arenaMenuButtonBack;
    private javax.swing.JButton arenaMenuButtonHeavyAttack;
    private javax.swing.JButton arenaMenuButtonLightAttack;
    private javax.swing.JButton arenaMenuButtonNormalAttack;
    public static javax.swing.JLabel changableLabelArmor;
    public static javax.swing.JLabel changableLabelDEX;
    public static javax.swing.JLabel changableLabelHP;
    public static javax.swing.JLabel changableLabelINT;
    public static javax.swing.JLabel changableLabelLevel;
    public static javax.swing.JLabel changableLabelMP;
    public static javax.swing.JLabel changableLabelMoney;
    public static javax.swing.JLabel changableLabelName;
    public static javax.swing.JLabel changableLabelSTR;
    public static javax.swing.JLabel changableLabelShield;
    public static javax.swing.JLabel changableLabelVIT;
    public static javax.swing.JLabel changableLabelWeapon;
    private javax.swing.ButtonGroup dificultyButtonGroup;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JButton heroStatsButtonBag;
    private javax.swing.JPanel heroStatsPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPanel mainMenuArenaMenu;
    private javax.swing.JButton mainMenuArenaMenuButtonArenaLevel;
    private javax.swing.JButton mainMenuArenaMenuButtonEnemyStats;
    private javax.swing.JButton mainMenuArenaMenuButtonFight;
    private javax.swing.JButton mainMenuArenaMenuButtonNextOpponent;
    private javax.swing.JButton mainMenuArenaMenuButtonOpponentConfirm;
    private javax.swing.JComboBox mainMenuArenaMenuComboBoxOpponentSelect;
    private javax.swing.JButton mainMenuButtonArena;
    private javax.swing.JButton mainMenuButtonHospital;
    private javax.swing.JButton mainMenuButtonNotYET;
    private javax.swing.JButton mainMenuButtonShop;
    private javax.swing.JPanel mainMenuShopMenu;
    private javax.swing.JButton mainMenuShopMenuButtonBuy;
    private javax.swing.JButton mainMenuShopMenuButtonSell;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuFileEndGame;
    private javax.swing.JMenuItem menuFileLoad;
    private javax.swing.JMenuItem menuFileNewGame;
    private javax.swing.JMenuItem menuFileSave;
    private javax.swing.JMenu menuHero;
    private javax.swing.JMenu menuSettings;
    private javax.swing.JLabel nameLabelArmor;
    private javax.swing.JLabel nameLabelDEX;
    private javax.swing.JLabel nameLabelHP;
    private javax.swing.JLabel nameLabelHeroStats;
    private javax.swing.JLabel nameLabelINT;
    private javax.swing.JLabel nameLabelLevel;
    private javax.swing.JLabel nameLabelMP;
    private javax.swing.JLabel nameLabelMoney;
    private javax.swing.JLabel nameLabelName;
    private javax.swing.JLabel nameLabelSTR;
    private javax.swing.JLabel nameLabelShield;
    private javax.swing.JLabel nameLabelVIT;
    private javax.swing.JLabel nameLabelWeapon;
    private javax.swing.JPanel panelArenaMenu;
    private javax.swing.JPanel panelMainMenu;
    private javax.swing.JPanel panelShopMenu;
    private javax.swing.JButton shopMenuButtonBack;
    private javax.swing.JButton shopMenuButtonBuy;
    private javax.swing.JLabel shopMenuLabelItemDEF;
    private javax.swing.JLabel shopMenuLabelItemDEFStats;
    private javax.swing.JLabel shopMenuLabelItemDEX;
    private javax.swing.JLabel shopMenuLabelItemDEXStats;
    private javax.swing.JLabel shopMenuLabelItemDMG;
    private javax.swing.JLabel shopMenuLabelItemDMGStats;
    private javax.swing.JLabel shopMenuLabelItemINT;
    private javax.swing.JLabel shopMenuLabelItemINTStats;
    private javax.swing.JLabel shopMenuLabelItemName;
    private javax.swing.JLabel shopMenuLabelItemNameStats;
    private javax.swing.JLabel shopMenuLabelItemPriceStats;
    private javax.swing.JLabel shopMenuLabelItemSTR;
    private javax.swing.JLabel shopMenuLabelItemSTRStats;
    private javax.swing.JLabel shopMenuLabelItemVIT;
    private javax.swing.JLabel shopMenuLabelItemVITStats;
    private javax.swing.JList shopMenuListField;
    private javax.swing.JRadioButtonMenuItem switchButtonDifficultyEasy;
    private javax.swing.JRadioButtonMenuItem switchButtonDifficultyHard;
    private javax.swing.JRadioButtonMenuItem switchButtonDifficultyNormal;
    private javax.swing.JCheckBoxMenuItem testButton;
    private javax.swing.JMenuItem testMenuAddDex;
    private javax.swing.JMenuItem testMenuAddInt;
    private javax.swing.JMenuItem testMenuAddStr;
    private javax.swing.JMenuItem testMenuAddVit;
    private javax.swing.JMenuBar topMenuBar;
    // End of variables declaration//GEN-END:variables
// </editor-fold> 
}
