/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Arena;

import Metods.Utilities;
import java.io.File;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Petr
 */
public class SaveForm extends javax.swing.JFrame {

    /**
     * Creates new form SaveForm
     */
    public SaveForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveFile = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        saveFile.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        File file = new File(System.getProperty("user.dir"));
        saveFile.setCurrentDirectory(file
        );
        FileNameExtensionFilter ff = new FileNameExtensionFilter("Arena Save", "as");
        saveFile.setDialogTitle("");
        saveFile.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);
        saveFile.setAutoscrolls(true);
        saveFile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        saveFile.setName(""); // NOI18N
        saveFile.setPreferredSize(new java.awt.Dimension(800, 470));
        saveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFileActionPerformed(evt);
            }
        });
        getContentPane().add(saveFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        saveFile.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFileActionPerformed
        path = null;

        System.out.println(saveFile.getName());
        if ("ApproveSelection".equals(evt.getActionCommand())) {
            try {
                if (saveFile.getSelectedFile().isDirectory() == true) {
                    saveFile.setCurrentDirectory(saveFile.getSelectedFile());
                } else {

                    String file = saveFile.getSelectedFile().getAbsolutePath();
                    path = file;
                    Utilities utilities = new Utilities();
                    utilities.saveProcess(getSavePath());
                    this.dispose();
                }
            } catch (Exception e) {
                System.out.println(e);

            }
        }


    }//GEN-LAST:event_saveFileActionPerformed

    public String getSavePath() {
        return path;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaveForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaveForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaveForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaveForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaveForm().setVisible(true);
            }
        });
    }
    private String path = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser saveFile;
    // End of variables declaration//GEN-END:variables
}
